### PR TITLE
 Link aubio from build.rs 

### PR DESCRIPTION
**Pull request by emmaworley**
I think this should be done in aubio-sys. Right now I have to do it in my binary.

### CODE REVIEW

**Review by katyo — APPROVED** [review]

**Comment by katyo** [comment]
Please fix the errors.

**Comment by emmaworley** [comment]
closing and reopening to re-trigger travis

**Comment by emmaworley** [comment]
looks like clippy is failing due to unrelated issues now

**Comment by katyo** [comment]
@connorworley,
I did some work to improve this bindings.
Particularly CI workflow now is based on GitHub Actions.
Also I switched to `cc` to avoid dealing with `waf` build system.
And the `aubio-lib` crate was merged with `aubio-sys`.
Could you help me to test pr #16 before I merge it?

**Pull request closed without merging**
